# Generated by Django 3.2.5 on 2021-07-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210702_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Equipo Biblioteca Bayer', max_length=50, verbose_name='Autor'),
        ),
    ]
