# Generated by Django 3.2.5 on 2021-07-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcom',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
