# Generated by Django 3.2.5 on 2021-07-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_subcom_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.AddField(
            model_name='article',
            name='subcomision',
            field=models.ManyToManyField(to='blog.SubCom', verbose_name='Subcomision'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
