# Generated by Django 3.2.5 on 2021-07-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210705_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Publico?'),
        ),
    ]
