# Generated by Django 3.2.5 on 2021-07-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_article_subcomision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['fecha'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
