# Generated by Django 3.2.5 on 2021-07-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210714_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='La Bayer Band', max_length=50, verbose_name='Autor'),
        ),
    ]
