# Generated by Django 3.2.5 on 2021-07-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_event_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subcomision',
            field=models.ManyToManyField(default='La Bayer Band', to='blog.SubCom', verbose_name='Subcomision'),
        ),
    ]
