# Generated by Django 3.2.5 on 2021-07-30 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_article_subcomision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha del evento'),
        ),
    ]
