# Generated by Django 3.2.5 on 2021-08-09 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_event_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha del evento'),
        ),
    ]
