# Generated by Django 3.2.5 on 2021-08-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_event_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fav',
            field=models.BooleanField(default=False, verbose_name='Relevante'),
        ),
    ]
